"use client";

import { useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";

type Kind = "budgets" | "goals" | "subscriptions" | "recurring" | "rules";
type Definition = { id: string; name: string };
type Item = Record<string, unknown> & { id: string };
type Suggestion = { patternKey:string; kind:"subscription"|"recurring"; merchant:string; category:string; cadence:string; occurrences:number; confidence:string; averageCents:number; monthlyCents:number; nextDate:string };
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const copy = {
  budgets: ["Plan", "Budgets", "Set category limits and compare them with real monthly spending.", "Create budget"],
  goals: ["Save with purpose", "Goals", "Track progress toward the things that matter to you.", "Create goal"],
  subscriptions: ["Commitments", "Subscriptions", "See renewals and the real monthly cost of your services.", "Add subscription"],
  recurring: ["Automatic detection", "Recurring", "Review repeating bills and plan for what comes next.", "Add recurring payment"],
  rules: ["Organize", "Rules & tags", "Create simple rules for future imports.", "Create rule"],
} as const;

export function EntityManager({ kind, initialItems, categories, accounts, suggestions }: { kind: Kind; initialItems: Item[]; categories: Definition[]; accounts: Definition[]; suggestions: Suggestion[] }) {
  const [items, setItems] = useState(initialItems); const [editing, setEditing] = useState<Item | null | "new">(null); const [message, setMessage] = useState("");
  const [visibleSuggestions,setVisibleSuggestions]=useState(suggestions.filter((item)=>item.kind===(kind==="subscriptions"?"subscription":"recurring")));
  const [eyebrow, title, description, action] = copy[kind];
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const payload: Record<string, unknown> = payloadFor(kind, form); if (editing !== "new" && editing) payload.id = editing.id;
    const response = await fetch(`/api/entities/${kind}`, { method: editing === "new" ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json();
    if (!response.ok) { setMessage(result.error ?? "Could not save."); return; }
    setItems((current) => editing === "new" ? [result.item, ...current] : current.map((item) => item.id === result.item.id ? result.item : item)); setEditing(null); setMessage(`${title.slice(0, -1)} saved.`);
  }
  async function remove(item: Item) { if (!window.confirm("Delete this item?")) return; const response = await fetch(`/api/entities/${kind}?id=${item.id}`, { method: "DELETE" }); if (response.ok) setItems((current) => current.filter((entry) => entry.id !== item.id)); else setMessage("Could not delete that item."); }
  async function toggleRule(item: Item) { const response = await fetch("/api/entities/rules", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, whenText: item.whenText, thenText: item.thenText, enabled: !item.enabled }) }); const result = await response.json(); if (response.ok) setItems((current) => current.map((entry) => entry.id === item.id ? result.item : entry)); else setMessage(result.error ?? "Could not update the rule."); }
  async function ignore(s:Suggestion){await fetch("/api/detection/ignore",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({patternKey:s.patternKey})});setVisibleSuggestions((current)=>current.filter((item)=>item.patternKey!==s.patternKey));}
  async function keep(s:Suggestion){const categoryId=categories.find((item)=>item.name===s.category)?.id??categories.find((item)=>item.name==="Needs review")?.id;const payload=kind==="subscriptions"?{serviceName:s.merchant,categoryId,amountCents:s.averageCents,cadence:s.cadence,nextRenewalDate:s.nextDate,accountId:null,active:true}:{name:s.merchant,categoryId,amountCents:s.averageCents,cadence:s.cadence,nextDate:s.nextDate,accountId:null,active:true};const response=await fetch(`/api/entities/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(response.ok){setItems((current)=>[result.item,...current]);setVisibleSuggestions((current)=>current.filter((item)=>item.patternKey!==s.patternKey));}else setMessage(result.error);}
  return <div className="page"><section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><button className="button primary" onClick={() => setEditing("new")}><Plus size={17} />{action}</button></section>{message && <p className="inline-message" role="status">{message}</p>}{visibleSuggestions.length>0&&<section className="suggestions"><p className="eyebrow">Detected from real transactions</p>{visibleSuggestions.map((s)=><article className="panel suggestion-card" key={s.patternKey}><div><h2>{s.merchant}</h2><p>{s.confidence} · {s.occurrences} occurrences · {s.cadence} · {money.format(s.monthlyCents/100)}/month</p></div><div><button className="button secondary" onClick={()=>ignore(s)}>Ignore</button><button className="button primary" onClick={()=>keep(s)}>Keep</button></div></article>)}</section>}<section className="entity-grid">{items.length === 0 ? <article className="panel section-empty"><h2>No {title.toLowerCase()} yet</h2><p>Your saved items will appear here.</p></article> : items.map((item) => <article className="panel entity-card" key={item.id}><div><h2>{displayName(kind, item)}</h2><p>{displayDetails(kind, item)}</p>{(kind==="budgets"||kind==="goals")&&<Progress kind={kind} item={item}/>}</div><div className="entity-actions">{kind === "rules" && <label className="rule-toggle"><input type="checkbox" checked={Boolean(item.enabled)} onChange={() => toggleRule(item)} /><span>Enabled</span></label>}<button className="icon-button small" aria-label="Edit" onClick={() => setEditing(item)}><Pencil size={15} /></button><button className="icon-button small" aria-label="Delete" onClick={() => remove(item)}><Trash2 size={15} /></button></div></article>)}</section>{editing && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><div className="modal-heading"><h2>{editing === "new" ? action : `Edit ${title.slice(0, -1)}`}</h2><button className="icon-button" onClick={() => setEditing(null)}><X /></button></div><EntityForm kind={kind} item={editing === "new" ? null : editing} categories={categories} accounts={accounts} onSubmit={save} onCancel={() => setEditing(null)} /></div></div>}</div>;
}

function EntityForm({ kind, item, categories, accounts, onSubmit, onCancel }: { kind: Kind; item: Item | null; categories: Definition[]; accounts: Definition[]; onSubmit: (e: React.FormEvent<HTMLFormElement>) => void; onCancel: () => void }) {
  const nameKey = kind === "subscriptions" ? "serviceName" : "name";
  return <form onSubmit={onSubmit}><div className="form-grid">{kind === "rules" ? <><label className="wide">When<input name="whenText" required defaultValue={String(item?.whenText ?? "")} placeholder="Merchant contains…" /></label><label className="wide">Then<input name="thenText" required defaultValue={String(item?.thenText ?? "")} placeholder="Set category or add tag…" /></label></> : kind !== "budgets" && <label className="wide">Name<input name={nameKey} required defaultValue={String(item?.[nameKey] ?? "")} /></label>}{kind !== "rules" && kind !== "goals" && <><label>Category<select name="categoryId" defaultValue={String(item?.categoryId ?? categories[0]?.id)}>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label></>}{kind === "goals" ? <><MoneyField name="target" label="Target amount" value={Number(item?.targetCents ?? 0)} /><MoneyField name="current" label="Current saved" value={Number(item?.currentCents ?? 0)} /><label>Due date<input type="date" name="dueDate" defaultValue={String(item?.dueDate ?? "")} /></label><label className="wide">Note<input name="note" defaultValue={String(item?.note ?? "")} /></label></> : kind === "budgets" ? <MoneyField name="amount" label="Monthly limit" value={Number(item?.monthlyLimitCents ?? 0)} /> : kind !== "rules" && <><MoneyField name="amount" label="Amount" value={Number(item?.amountCents ?? 0)} /><label>Cadence<select name="cadence" defaultValue={String(item?.cadence ?? "monthly")}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></label><label>{kind === "subscriptions" ? "Next renewal" : "Next date"}<input type="date" name="nextDate" required defaultValue={String(item?.[kind === "subscriptions" ? "nextRenewalDate" : "nextDate"] ?? "")} /></label><label>Account<select name="accountId" defaultValue={String(item?.accountId ?? "")}><option value="">None</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label></>}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary">Save</button></div></form>;
}
function MoneyField({ name, label, value }: { name: string; label: string; value: number }) { return <label>{label}<input name={name} type="number" min="0.01" step="0.01" required defaultValue={value ? value / 100 : ""} /></label>; }
function payloadFor(kind: Kind, form: FormData) { const v = (key: string) => String(form.get(key) ?? ""); if (kind === "goals") return { name: v("name"), targetCents: Math.round(Number(v("target")) * 100), currentCents: Math.round(Number(v("current")) * 100), dueDate: v("dueDate") || null, note: v("note") || null }; if (kind === "budgets") return { categoryId: v("categoryId"), monthlyLimitCents: Math.round(Number(v("amount")) * 100), active: true }; if (kind === "rules") return { whenText: v("whenText"), thenText: v("thenText"), enabled: true }; return { [kind === "subscriptions" ? "serviceName" : "name"]: v(kind === "subscriptions" ? "serviceName" : "name"), categoryId: v("categoryId"), amountCents: Math.round(Number(v("amount")) * 100), cadence: v("cadence"), [kind === "subscriptions" ? "nextRenewalDate" : "nextDate"]: v("nextDate"), accountId: v("accountId") || null, active: true }; }
function displayName(kind: Kind, item: Item) { return String(kind === "subscriptions" ? item.serviceName : kind === "budgets" ? item.categoryLabel : kind === "rules" ? `When ${item.whenText}` : item.name); }
function displayDetails(kind: Kind, item: Item) { if (kind === "rules") return `Then ${item.thenText}`; if (kind === "goals") return `${money.format(Number(item.currentCents) / 100)} of ${money.format(Number(item.targetCents) / 100)}`; if (kind === "budgets") return `${money.format(Number(item.spentCents??0)/100)} spent of ${money.format(Number(item.monthlyLimitCents) / 100)}`; return `${money.format(Number(item.amountCents) / 100)} · ${String(item.cadence)}`; }
function Progress({kind,item}:{kind:"budgets"|"goals";item:Item}){const current=Number(kind==="budgets"?item.spentCents:item.currentCents);const target=Number(kind==="budgets"?item.monthlyLimitCents:item.targetCents);const percent=target?Math.max(0,Math.round(current/target*100)):0;return <div className={`progress-track ${percent>100?"over":""}`} aria-label={`${percent}%`}><i style={{width:`${Math.min(percent,100)}%`}}/><span>{percent}%</span></div>}
