import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { getDatabase } from "@/lib/db";
import { dataRoot } from "@/lib/runtime-paths";
import { storeDocument } from "@/lib/documents";

export function discoverDriveInbox() {
  if (process.env.LEDGERLY_DRIVE_INBOX) return path.resolve(process.env.LEDGERLY_DRIVE_INBOX);
  const cloud=path.join(os.homedir(),"Library","CloudStorage"); const matches:string[]=[];
  for(const root of fs.readdirSync(cloud,{withFileTypes:true}).filter((e)=>e.isDirectory()&&e.name.startsWith("GoogleDrive-"))) { const candidate=path.join(cloud,root.name,"My Drive","Ledgerly Financial Inbox"); if(fs.existsSync(candidate)&&fs.statSync(candidate).isDirectory()) matches.push(candidate); }
  if(matches.length!==1) throw new Error(matches.length?"Multiple Ledgerly inboxes found.":"Ledgerly inbox is not synchronized yet."); return matches[0];
}
export async function syncDriveInbox(){const inbox=discoverDriveInbox();const lock=path.join(dataRoot,"drive-sync.lock");fs.mkdirSync(dataRoot,{recursive:true,mode:0o700});let handle;try{handle=fs.openSync(lock,"wx",0o600);}catch{return {status:"already-running"};}const result={status:"complete",stored:0,review:0,skipped:0,errors:[] as string[]};const db=getDatabase();try{const resetRow=db.prepare("SELECT value FROM settings WHERE key='driveResetAt'").get() as {value:string}|undefined;const resetAt=resetRow?String(JSON.parse(resetRow.value)):"";for(const entry of fs.readdirSync(inbox,{withFileTypes:true})){if(!entry.isFile()||entry.name.startsWith("."))continue;const full=path.join(inbox,entry.name);try{const stat=fs.statSync(full);if(stat.size===0||stat.size>20*1024*1024||new Date(stat.mtimeMs).toISOString()<=resetAt){result.skipped++;continue;}const fileId=crypto.createHash("sha256").update(entry.name).digest("hex");const modifiedAt=new Date(stat.mtimeMs).toISOString();const prior=db.prepare("SELECT modifiedAt,status FROM drive_files WHERE fileId=?").get(fileId) as {modifiedAt:string;status:string}|undefined;if(prior&&prior.modifiedAt===modifiedAt&&["stored","review"].includes(prior.status)){result.skipped++;continue;}const bytes=fs.readFileSync(full);const extension=path.extname(entry.name).toLowerCase();const mime=extension===".txt"?"text/plain":extension===".csv"?"text/csv":"";const file=new File([bytes],entry.name,{type:mime});const document=await storeDocument(file,null,{source:"google-drive",driveFileId:fileId,driveModifiedAt:modifiedAt});db.prepare(`INSERT INTO drive_files(fileId,relativePath,modifiedAt,size,sha256,status,processedAt,lastError) VALUES(?,?,?,?,?,?,?,NULL) ON CONFLICT(fileId) DO UPDATE SET modifiedAt=excluded.modifiedAt,size=excluded.size,sha256=excluded.sha256,status=excluded.status,processedAt=excluded.processedAt,lastError=NULL`).run(fileId,entry.name,modifiedAt,stat.size,crypto.createHash("sha256").update(bytes).digest("hex"),document.status,new Date().toISOString());result.stored++;if(document.status==="review")result.review++;}catch{result.status="partial";result.errors.push(`Could not import ${entry.name.slice(0,80)}.`);}}const now=new Date().toISOString();db.prepare(`INSERT INTO settings(key,value,updatedAt) VALUES('driveInboxPath',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updatedAt=excluded.updatedAt`).run(JSON.stringify(inbox),now);return result;}finally{if(handle)fs.closeSync(handle);fs.rmSync(lock,{force:true});}}
